name: idea_cache
description: "A Flutter Project for caching chaotic idea."
publish_to: 'Github'
version: 1.3.2

environment:
  sdk: ^3.8.1

dependencies:
  window_manager: ^0.5.0
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  convert: ^3.1.2
  uuid: ^4.5.1
  flutter_quill: ^11.4.1
  provider: ^6.1.5
  flutter_launcher_icons: ^0.14.4
  file_picker: ^10.2.0
  flutter_local_notifications: ^19.4.0
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3
  sqflite_common_ffi: ^2.3.6
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  audioplayers: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
dependency_overrides: 
  flutter_quill:
    git:
      url: https://github.com/theniceboy/flutter-quill.git
      ref: fix-flutter-3-32-macos-crash
flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
  fonts:
    - family: Abel
      fonts:
        - asset: assets/fonts/Abel-Regular.ttf

    - family: EB Garamond
      fonts:
        - asset: assets/fonts/EBGaramond-VariableFont_wght.ttf

    - family: Coda
      fonts:
        - asset: assets/fonts/Coda-Regular.ttf

    - family: FiraCode Nerd Font
      fonts:
        - asset: assets/fonts/FiraCodeNerdFont-Regular.ttf

    - family: Annie Use Your Telescope
      fonts:
        - asset: assets/fonts/AnnieUseYourTelescope-Regular.ttf

    - family: Noto Serif Thin
      fonts: 
        - asset: assets/fonts/NotoSerif-VariableFont_wdth,wght.ttf

    - family: Noto Sans Thin
      fonts: 
        - asset: assets/fonts/NotoSans-VariableFont_wdth,wght.ttf

    - family: Roboto Thin
      fonts: 
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf
  # assets:

  #   - assets/images/

